# Generated by Django 5.2.6 on 2025-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='No notes yet'),
            preserve_default=False,
        ),
    ]
