# Generated by Django 5.2.6 on 2025-09-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
