# Generated by Django 5.2.6 on 2025-09-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_ninjas_created_at_ninjas_first_name_ninjas_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='old Dojo'),
            preserve_default=False,
        ),
    ]
